parameters:
   snowio_connector.job.job_parameters.default_values_provider.product.class: Snowio\Bundle\CsvConnectorBundle\Job\JobParameters\DefaultValuesProvider\ProductDefaultValues
   snowio_connector.job.job_parameters.default_values_provider.simple.class: Snowio\Bundle\CsvConnectorBundle\Job\JobParameters\DefaultValuesProvider\SimpleDefaultValues

services:
    snowio_connector.job.job_parameters.default_values_provider.full_export:
        class: '%snowio_connector.job.job_parameters.default_values_provider.product.class%'
        arguments:
            - '@pim_connector.job.job_parameters.default_values_provider.simple_csv_export'
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.repository.locale'
            - ['full_export']
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }

    snowio_connector.job.job_parameters.default_values_provider.partial_export:
        class: '%snowio_connector.job.job_parameters.default_values_provider.simple.class%'
        arguments:
            - ['partial_export']
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }
