extensions:
    snowio-csv-product-export-show:
        module: pim/form/common/edit-form

    snowio-csv-product-export-show-tabs:
        module: pim/form/common/form-tabs
        parent: snowio-csv-product-export-show
        targetZone: content
        position: 100

    snowio-csv-product-export-show-properties:
        module: pim/job/common/edit/properties
        parent: snowio-csv-product-export-show-tabs
        aclResourceId: pim_importexport_export_profile_property_show
        targetZone: container
        position: 100
        config:
            tabTitle: pim_enrich.form.job_instance.tab.properties.title
            tabCode: pim-properties

    snowio-csv-product-export-show-content:
          module: pim/job/product/edit/content
          parent: snowio-csv-product-export-show-tabs
          aclResourceId: pim_importexport_export_profile_content_show
          targetZone: container
          position: 110
          config:
              tabTitle: pim_enrich.form.job_instance.tab.content.title
              tabCode: pim-job-instance-content

    snowio-csv-product-export-show-history:
        module: pim/common/tab/history
        parent: snowio-csv-product-export-show-tabs
        targetZone: container
        aclResourceId: pim_importexport_export_profile_history
        position: 120
        config:
            class: Akeneo\Component\Batch\Model\JobInstance
            title: pim_enrich.form.job_instance.tab.history.title
            tabCode: pim-history

    snowio-csv-product-export-show-properties-code:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-product-export-show-properties
        position: 100
        targetZone: properties
        config:
            fieldCode: code
            label: pim_enrich.form.job_instance.tab.properties.code.title
            readOnly: true

    snowio-csv-product-export-show-properties-label:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-product-export-show-properties
        position: 110
        targetZone: properties
        config:
            fieldCode: label
            label: pim_enrich.form.job_instance.tab.properties.label.title
            readOnly: true

    snowio-csv-product-export-show-properties-decimal-separator:
        module: pim/job/common/edit/field/decimal-separator
        parent: snowio-csv-product-export-show-properties
        position: 130
        targetZone: global-settings
        config:
            fieldCode: configuration.decimalSeparator
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.decimal_separator.title
            tooltip: pim_enrich.form.job_instance.tab.properties.decimal_separator.help

    snowio-csv-product-export-show-properties-date-format:
        module: pim/job/product/edit/field/date-format
        parent: snowio-csv-product-export-show-properties
        position: 140
        targetZone: global-settings
        config:
            fieldCode: configuration.dateFormat
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.date_format.title
            tooltip: pim_enrich.form.job_instance.tab.properties.date_format.help

    snowio-csv-product-export-show-properties-delimiter:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-product-export-show-properties
        position: 150
        targetZone: global-settings
        config:
            fieldCode: configuration.delimiter
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.delimiter.title
            tooltip: pim_enrich.form.job_instance.tab.properties.delimiter.help

    snowio-csv-product-export-show-properties-enclosure:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-product-export-show-properties
        position: 160
        targetZone: global-settings
        config:
            fieldCode: configuration.enclosure
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.enclosure.title
            tooltip: pim_enrich.form.job_instance.tab.properties.enclosure.help

    snowio-csv-product-export-show-properties-with-header:
        module: pim/job/common/edit/field/switch
        parent: snowio-csv-product-export-show-properties
        position: 170
        targetZone: global-settings
        config:
            fieldCode: configuration.withHeader
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.with_header.title
            tooltip: pim_enrich.form.job_instance.tab.properties.with_header.help

    snowio-csv-product-export-show-properties-with-media:
        module: pim/job/common/edit/field/switch
        parent: snowio-csv-product-export-show-properties
        position: 180
        targetZone: global-settings
        config:
            fieldCode: configuration.with_media
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.with_media.title
            tooltip: pim_enrich.form.job_instance.tab.properties.with_media.help

    snowio-csv-product-export-show-properties-endpoint:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-product-export-show-properties
        position: 190
        targetZone: global-settings
        config:
            fieldCode: configuration.endpoint
            readOnly: true
            label: snowio_connector.form.job_instance.tab.properties.endpoint.title
            tooltip: snowio_connector.form.job_instance.tab.properties.endpoint.help

    snowio-csv-product-export-show-properties-secret-key:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-product-export-show-properties
        position: 200
        targetZone: global-settings
        config:
            fieldCode: configuration.secretKey
            readOnly: true
            label: snowio_connector.form.job_instance.tab.properties.secret_key.title
            tooltip: snowio_connector.form.job_instance.tab.properties.secret_key.help

    snowio-csv-product-export-show-properties-application-id:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-product-export-show-properties
        position: 210
        targetZone: global-settings
        config:
            fieldCode: configuration.applicationId
            readOnly: true
            label: snowio_connector.form.job_instance.tab.properties.application_id.title
            tooltip: snowio_connector.form.job_instance.tab.properties.application_id.help

    snowio-csv-product-export-show-properties-export-dir:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-product-export-show-properties
        position: 220
        targetZone: global-settings
        config:
            fieldCode: configuration.exportDir
            readOnly: true
            label: snowio_connector.form.job_instance.tab.properties.export_dir.title
            tooltip: snowio_connector.form.job_instance.tab.properties.export_dir.help

    snowio-csv-product-export-show-properties-rsync-directory:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-product-export-show-properties
        position: 230
        targetZone: global-settings
        config:
            fieldCode: configuration.rsyncDirectory
            readOnly: true
            label: snowio_connector.form.job_instance.tab.properties.rsync_directory.title
            tooltip: snowio_connector.form.job_instance.tab.properties.rsync_directory.help

    snowio-csv-product-export-show-properties-rsync-user:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-product-export-show-properties
        position: 240
        targetZone: global-settings
        config:
            fieldCode: configuration.rsyncUser
            readOnly: true
            label: snowio_connector.form.job_instance.tab.properties.rsync_user.title
            tooltip: snowio_connector.form.job_instance.tab.properties.rsync_user.help

    snowio-csv-product-export-show-properties-rsync-host:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-product-export-show-properties
        position: 250
        targetZone: global-settings
        config:
            fieldCode: configuration.rsyncHost
            readOnly: true
            label: snowio_connector.form.job_instance.tab.properties.rsync_host.title
            tooltip: snowio_connector.form.job_instance.tab.properties.rsync_host.help

    snowio-csv-product-export-show-properties-rsync-options:
        module: pim/job/common/edit/field/text
        parent: snowio-csv-product-export-show-properties
        position: 240
        targetZone: global-settings
        config:
            fieldCode: configuration.rsyncOptions
            readOnly: true
            label: snowio_connector.form.job_instance.tab.properties.rsync_options.title
            tooltip: snowio_connector.form.job_instance.tab.properties.rsync_options.help

    snowio-csv-product-export-show-content-structure:
        module: pim/job/product/edit/content/structure
        parent: snowio-csv-product-export-show-content
        targetZone: structure-filters
        position: 100

    snowio-csv-product-export-show-label:
        module: pim/job/common/edit/label
        parent: snowio-csv-product-export-show
        targetZone: title
        position: 100

    snowio-csv-product-export-show-meta:
        module: pim/job/common/edit/meta
        parent: snowio-csv-product-export-show
        targetZone: meta
        position: 100

    snowio-csv-product-export-show-back-to-grid:
        module: pim/form/common/back-to-grid
        parent: snowio-csv-product-export-show
        targetZone: back
        aclResourceId: pim_importexport_export_profile_index
        position: 80
        config:
            backUrl: pim_importexport_export_profile_index

    snowio-csv-product-export-show-content-structure-scope:
        module: pim/job/product/edit/content/structure/scope
        parent: snowio-csv-product-export-show-content-structure
        targetZone: filters
        position: 90
        config:
            readOnly: true

    snowio-csv-product-export-show-content-structure-locales:
        module: pim/job/product/edit/content/structure/locales
        parent: snowio-csv-product-export-show-content-structure
        targetZone: filters
        position: 100
        config:
            readOnly: true

    snowio-csv-product-export-show-content-structure-attributes:
        module: pim/job/product/edit/content/structure/attributes
        parent: snowio-csv-product-export-show-content-structure
        targetZone: filters
        position: 110
        config:
            readOnly: true

    snowio-csv-product-export-show-content-data:
        module: pim/job/product/edit/content/data
        parent: snowio-csv-product-export-show-content
        targetZone: data-filters
        config:
            filters:
                -
                    field: family
                    view: akeneo-product-family-filter
                -
                    field: enabled
                    view: akeneo-product-enabled-filter
                -
                    field: completeness
                    view: akeneo-product-completeness-filter
                -
                    field: updated
                    view: akeneo-product-updated-filter
                -
                    field: categories
                    view: akeneo-product-category-filter

    snowio-csv-product-export-show-edit:
        module: pim/common/redirect
        parent: snowio-csv-product-export-show
        targetZone: buttons
        position: 100
        config:
            label: pim_enrich.form.job_instance.button.edit.title
            route: pim_importexport_export_profile_edit
            identifier:
                path: code
                name: code

    snowio-csv-product-export-show-launch:
        module: pim/job/common/edit/launch
        parent: snowio-csv-product-export-show
        targetZone: buttons
        position: 110
        config:
            label: pim_enrich.form.job_instance.button.export.title
            route: pim_enrich_job_instance_rest_export_launch
            identifier:
                path: code
                name: code
